export const f={
  text:(name,label,x={})=>({name,label,type:"text",...x}),
  url:(name,label,x={})=>({name,label,type:"url",...x}),
  area:(name,label,x={})=>({name,label,type:"textarea",wide:true,...x}),
  html:(name,label,x={})=>({name,label,type:"html",wide:true,...x}),
  num:(name,label,x={})=>({name,label,type:"number",...x}),
  sort:(name,label="Thứ tự hiển thị",x={})=>({name,label,type:"sort",min:1,step:1,...x}),
  bool:(name,label,x={})=>({name,label,type:"checkbox",...x}),
  json:(name,label,x={})=>({name,label,type:"json",wide:true,...x}),
  arr:(name,label,x={})=>({name,label,type:"array",wide:true,...x}),
  sel:(name,label,options,x={})=>({name,label,type:"select",options,...x}),
  dt:(name,label,x={})=>({name,label,type:"datetime",...x}),
  color:(name,label,x={})=>({name,label,type:"color",...x}),
  relation:(name,label,relation,x={})=>({name,label,type:"relation",relation,...x}),
  checks:(name,label,relation,x={})=>({name,label,type:"checks",relation,...x}),
  checkOptions:(name,label,options,x={})=>({name,label,type:"checks",options,...x}),
  media:(name,label,x={})=>({name,label,type:"media",wide:true,...x}),
  hidden:(name,x={})=>({name,label:name,type:"text",hidden:true,...x}),
};
