import React,{useEffect,useState}from"react";import TableManager from"../components/TableManager";import{AdminPage}from"./_shared";import{f}from"../schema";import{supabase,invoke}from"../lib/supabase";import{notify}from"../lib/notify";
function randomSecret(){const b=new Uint8Array(48);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,"0")).join("")}
function nextSlot(){const d=new Date(Date.now()+15*60*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
export default function Api({access}){const[ints,setInts]=useState([]),[id,setId]=useState(""),[secret,setSecret]=useState(""),[msg,setMsg]=useState(""),[cloudSecret,setCloudSecret]=useState("");async function load(){const{data}=await supabase.from("api_integrations").select("id,name,secret_updated_at").order("name");setInts(data||[])}useEffect(()=>{load()},[]);async function saveSecret(){try{const r=await invoke("integration-secret",{integration_id:id,secret});const m=r.message||"Đã lưu secret.";setMsg(m);notify(m,"success");setSecret("");load()}catch(e){setMsg(e.message);notify(e.message,"error",6500)}}
return <AdminPage access={access}>
<TableManager title="Kết nối API" description="Mỗi kết nối định nghĩa dịch vụ bên ngoài mà website được gọi. API key thật không lưu trong HTML/browser; nhập riêng ở khối API Secret bên dưới." table="api_integrations" defaults={{method:"POST",scope:"authenticated",timeout_ms:30000,active:false,headers_template:{"Authorization":"Bearer {{API_KEY}}","Content-Type":"application/json"},query_template:{},body_template:{},key_placeholder:"{{API_KEY}}"}} fields={[
 f.text("slug","Mã kết nối",{required:true,placeholder:"ilovepdf",help:"Mã nội bộ duy nhất để tool/scheduler gọi integration."}),f.text("name","Tên kết nối",{required:true,placeholder:"iLovePDF"}),f.area("description","Mô tả",{placeholder:"API này dùng cho chức năng gì…"}),f.url("base_url","Base URL",{required:true,placeholder:"https://api.example.com",help:"Domain gốc của API."}),f.text("allowed_host","Host được phép",{required:true,placeholder:"api.example.com",help:"Lớp bảo vệ SSRF: Edge Function chỉ được gọi đúng hostname này."}),f.text("endpoint_template","Endpoint",{required:true,placeholder:"/v1/process",help:"Đường dẫn API phía sau Base URL. Có thể dùng biến payload theo cấu hình integration."}),f.sel("method","HTTP method",["GET","POST","PUT","PATCH","DELETE"].map(x=>({value:x,label:x})),{required:true,help:"Phương thức API yêu cầu."}),f.json("headers_template","Headers",{help:"Header gửi tới API. Dùng {{API_KEY}} tại vị trí secret; hệ thống thay giá trị ở Edge Function."}),f.json("query_template","Query parameters",{help:"Các tham số gắn sau dấu ? của URL. Giữ {} nếu không dùng."}),f.json("body_template","Body mẫu",{help:"JSON body mặc định. Payload thực tế có thể bổ sung khi gọi."}),f.text("key_placeholder","Ký hiệu API key",{required:true,placeholder:"{{API_KEY}}",help:"Chuỗi trong template sẽ được thay bằng secret đã mã hóa."}),f.sel("scope","Ai được gọi",[{value:"public",label:"Public — ai cũng có thể gọi"},{value:"authenticated",label:"Authenticated — cần đăng nhập"},{value:"admin",label:"Admin — chỉ quản trị"}],{required:true,help:"Phạm vi gọi proxy; API tốn phí nên tránh Public nếu không cần."}),f.num("timeout_ms","Timeout (ms)",{required:true,min:1000,max:60000,step:1000,help:"Thời gian tối đa chờ API, ví dụ 30000 = 30 giây."}),f.bool("active","Kích hoạt",{trueLabel:"Cho phép dùng kết nối này"})
]}/>
<section className="adminSection"><div className="sectionTitle"><div><h1>API Secret</h1><p className="sectionDescription">Chọn kết nối rồi nhập API key. Key được mã hóa ở Edge Function; Admin không đọc ngược lại sau khi lưu.</p></div></div><div className="uploadBox"><select value={id} onChange={e=>setId(e.target.value)}><option value="">— Chọn kết nối —</option>{ints.map(x=><option key={x.id} value={x.id}>{x.name}{x.secret_updated_at?" · đã có key":""}</option>)}</select><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="API secret/key"/><button className="primary" onClick={saveSecret} disabled={!id||!secret}>Mã hóa & lưu</button></div>{msg&&<div className="notice">{msg}</div>}</section>
<TableManager title="Lịch chạy API" description="Lịch này chạy trên cloud qua GitHub Actions → Supabase Edge Function; không phụ thuộc máy tính của bạn bật hay tắt." table="scheduled_api_jobs" orderBy="next_run_at" ascending defaults={{handler:"integration",request_payload:{},interval_minutes:1440,enabled:true,next_run_at:nextSlot}} fields={[
 f.relation("integration_id","Kết nối API",{table:"api_integrations",select:"id,name,slug",valueKey:"id",label:o=>`${o.name} (${o.slug})`,orderBy:"name"},{nullable:true,showWhen:form=>form.handler==="integration",requiredWhen:form=>form.handler==="integration",derive:form=>form.handler==="integration"?form.integration_id:null,placeholder:"— Không cần cho keepalive —",help:"Bắt buộc khi Loại tác vụ = Integration. Khi Handler = Supabase keepalive thì để trống."}),f.text("name","Tên lịch",{required:true,placeholder:"Đồng bộ dữ liệu mỗi ngày"}),f.sel("handler","Loại tác vụ",[{value:"integration",label:"Integration — gọi kết nối API bên trên"},{value:"supabase_keepalive",label:"Supabase keepalive — truy vấn nhẹ định kỳ"}],{required:true,help:"Integration chạy một API đã cấu hình. Keepalive chỉ thực hiện truy vấn nhẹ để duy trì hoạt động theo nhu cầu của bạn."}),f.text("endpoint_path","Ghi chú endpoint",{placeholder:"Để trống nếu integration đã có endpoint",help:"Trường tương thích/ghi chú đường dẫn; integration chính lấy endpoint từ Kết nối API."}),f.json("request_payload","Payload khi chạy",{help:"Dữ liệu JSON gửi mỗi lần lịch chạy. Giữ {} nếu API không cần input cố định."}),f.num("interval_minutes","Chu kỳ (phút)",{required:true,min:15,max:525600,step:1,placeholder:"1440",help:"Ví dụ 60 = mỗi giờ, 1440 = mỗi ngày, 10080 = mỗi tuần. Scheduler cloud kiểm tra mỗi 15 phút; job đến hạn sẽ chạy ở lượt kiểm tra kế tiếp."}),f.bool("enabled","Bật lịch",{trueLabel:"Cho phép lịch này chạy"}),f.dt("next_run_at","Lần chạy kế tiếp",{required:true,help:"Mốc thời gian lần tới; sau khi chạy hệ thống tự cộng chu kỳ."})
]}/>
<section className="adminSection"><div className="sectionTitle"><div><h1>Khóa Scheduler trên cloud</h1><p className="sectionDescription">Không dùng lệnh PowerShell GUID nữa. Nút dưới đây tạo khóa bằng Web Crypto. Sau đó lưu cùng một giá trị vào Supabase Edge Function Secret và GitHub Actions Secret. Máy tính tắt không làm khóa mất hiệu lực vì khóa được lưu trên hai dịch vụ cloud.</p></div></div><div className="secretGenerator"><button className="primary" onClick={()=>setCloudSecret(randomSecret())}>Tạo khóa ngẫu nhiên an toàn</button>{cloudSecret&&<><textarea readOnly value={cloudSecret}/><button onClick={()=>navigator.clipboard.writeText(cloudSecret)}>Copy</button><small>Lưu thành SCHEDULER_SECRET ở Supabase và GitHub; không commit vào source.</small></>}</div></section>
</AdminPage>}
