import React,{useEffect,useState}from"react";import TableManager from"../components/TableManager";import{AdminPage}from"./_shared";import{f}from"../schema";import{supabase}from"../lib/supabase";
const themeTemplate={layout:"source-default",accent:"blue",show_photo:true,show_contact:true,show_download_pdf:true};
function Sections(){const[profileId,setProfileId]=useState(null);useEffect(()=>{supabase.from("cv_profiles").select("id").order("updated_at",{ascending:false}).limit(1).maybeSingle().then(({data})=>setProfileId(data?.id||null))},[]);if(!profileId)return <section className="adminSection"><div className="notice">Chưa có hồ sơ CV để thêm mục.</div></section>;return <TableManager title="Các mục trong CV" description="Thêm/bớt kinh nghiệm, học vấn, chứng chỉ, kỹ năng… Mỗi mục có nút Hiển thị để ẩn/hiện mà không phải xóa. Thứ tự tự tăng 1, 2, 3…" table="cv_sections" orderBy="sort_order" ascending defaults={{profile_id:profileId,section_type:"experience",visible:true,data:{}}} fields={[
 f.hidden("profile_id"),f.sel("section_type","Loại mục",[{value:"experience",label:"Kinh nghiệm"},{value:"education",label:"Học vấn"},{value:"certificate",label:"Chứng chỉ"},{value:"skill",label:"Kỹ năng"},{value:"project",label:"Dự án"},{value:"language",label:"Ngôn ngữ"},{value:"custom",label:"Tùy chỉnh"}],{required:true,help:"Loại quyết định cách frontend nhóm/hiển thị mục."}),
 f.text("title_vi","Tiêu đề (VI)",{required:true,placeholder:"Kỹ sư thiết kế / AutoCAD / Tự động hóa…"}),f.text("title_en","Tiêu đề (EN)",{placeholder:"Optional…"}),f.text("subtitle_vi","Dòng phụ (VI)",{placeholder:"Ví dụ: Hệ kỹ sư · Tốt nghiệp loại Giỏi"}),f.text("subtitle_en","Dòng phụ (EN)",{placeholder:"Optional…"}),f.text("period","Thời gian",{placeholder:"06/2025 - 11/2025",help:"Có thể để trống với kỹ năng/chứng chỉ không cần mốc thời gian."}),f.text("organization","Tổ chức / công ty (VI)",{placeholder:"Công ty / trường học…"}),f.text("organization_en","Tổ chức / công ty (EN)",{placeholder:"Optional English organization…"}),f.area("description_vi","Mô tả (VI)",{placeholder:"Công việc/thành tích…"}),f.area("description_en","Mô tả (EN)",{placeholder:"Optional…"}),f.url("url","Liên kết",{nullable:true,placeholder:"https://...",help:"Link chứng chỉ/dự án nếu có."}),f.sort("sort_order","Thứ tự",{required:true}),f.bool("visible","Hiển thị mục",{trueLabel:"Hiển thị mục này trong CV"}),f.json("data","Dữ liệu mở rộng",{help:"Giữ {} nếu mục này không cần tham số đặc biệt."})
]}/>}
export default function Cv({access}){return <AdminPage access={access}><TableManager title="Hồ sơ CV chính" description="Website dùng một hồ sơ CV chính. Admin chỉ sửa nội dung; không tạo nhiều profile trùng. Dữ liệu mẫu bám theo public/content/cv/profile.json của source NLKH_KOHA hiện tại." table="cv_profiles" singleRow allowAdd={false} allowDelete={false} defaults={{theme:themeTemplate,published:true,pdf_access:"public"}} fields={[
 f.text("name","Họ và tên",{required:true,placeholder:"Nguyễn Lê Khánh Hòa"}),f.text("role_vi","Chức danh (VI)",{required:true,placeholder:"Kỹ sư điện"}),f.text("role_en","Chức danh (EN)",{placeholder:"Electrical Engineer"}),f.area("headline_vi","Headline (VI)",{placeholder:"Một câu ngắn giới thiệu nghề nghiệp…"}),f.area("headline_en","Headline (EN)",{placeholder:"Optional…"}),f.area("summary_vi","Tóm tắt (VI)",{required:true,placeholder:"Tóm tắt năng lực/kinh nghiệm…"}),f.area("summary_en","Tóm tắt (EN)",{placeholder:"Optional…"}),f.text("birth_date","Ngày sinh",{nullable:true,placeholder:"15/05/2002",help:"Giữ dạng ngày/tháng/năm nếu muốn hiển thị giống source hiện tại."}),f.text("address_vi","Địa chỉ (VI)",{placeholder:"Thanh Xuân, Hà Nội"}),f.text("address_en","Địa chỉ (EN)",{placeholder:"Thanh Xuan, Hanoi"}),f.text("phone","Điện thoại",{nullable:true,placeholder:"0343 434 584"}),f.text("email","Email",{nullable:true,placeholder:"khanhhoa2002.hh@gmail.com"}),
 f.media("photo_media_id","Ảnh chân dung",{kind:"image",mirrorUrlField:"photo_url",help:"Tải/chọn ảnh R2 ngay tại đây. Nếu bỏ trống, frontend có thể dùng ảnh source mặc định."}),f.hidden("photo_url"),
 f.sel("pdf_access","Quyền tải file PDF CV",[{value:"public",label:"Công khai — ai cũng tải được"},{value:"authenticated",label:"Cần đăng nhập mới tải"},{value:"hidden",label:"Ẩn nút tải PDF"}],{required:true,help:"Khác với 'Hiển thị hồ sơ'. Ô này chỉ điều khiển file PDF tải xuống: Public = ai cũng tải; Authenticated = cần login; Hidden = không hiện nút tải."}),
 f.media("pdf_media_id","File PDF CV",{kind:"pdf",mirrorUrlField:"pdf_url",visibility:form=>form.pdf_access==="public"?"public":form.pdf_access==="authenticated"?"authenticated":"private",showWhen:form=>form.pdf_access!=="hidden",requiredWhen:form=>form.pdf_access==="authenticated",help:"Tải PDF mới hoặc chọn lại ID R2 cũ ngay tại đây. Nếu chọn Cần đăng nhập thì bắt buộc dùng file R2 mức Authenticated; không dùng file static public vì người biết URL có thể tải trực tiếp. Public có thể để trống để giữ PDF source mặc định."}),f.hidden("pdf_url"),
 f.json("theme","Giao diện CV",{placeholder:JSON.stringify(themeTemplate,null,2),help:"Cấu hình giao diện. Mẫu gốc: layout=source-default, accent=blue, show_photo=true. Nếu chưa muốn đổi giao diện, giữ nguyên mẫu này."}),
 f.bool("published","Hiển thị hồ sơ",{trueLabel:"Hiển thị CV trên website",help:"Đây là trạng thái ẩn/hiện hồ sơ, không phải quyền file R2. Tắt = trang CV không công khai nội dung hồ sơ."})
]}/><Sections/></AdminPage>}
