import React from"react";import TableManager from"../components/TableManager";import DataAccessMatrix from"../components/DataAccessMatrix";import{AdminPage}from"./_shared";import{f}from"../schema";
const groupRel={table:"data_collections",select:"id,name_vi,slug,sort_order",valueKey:"id",label:o=>`${o.name_vi} (${o.slug})`,orderBy:"sort_order"};
export default function Data({access}){return <AdminPage access={access}>
<TableManager title="Nhóm dữ liệu (tùy chọn)" description="Nhóm chỉ để gom nhiều tài liệu cùng chủ đề như Kỹ thuật điện/COMTRADE. Không bắt buộc; nếu ít tài liệu có thể để mục dữ liệu ở trạng thái không phân nhóm." table="data_collections" orderBy="sort_order" ascending defaults={{visibility:"private",visible:true}} fields={[
 f.text("slug","Slug nhóm",{required:true,placeholder:"ky-thuat-dien"}),f.text("name_vi","Tên nhóm",{required:true,placeholder:"Kỹ thuật điện"}),f.text("name_en","Tên EN",{placeholder:"Electrical engineering"}),f.area("description_vi","Mô tả",{placeholder:"Nhóm chứa tài liệu gì…"}),f.area("description_en","Mô tả EN",{placeholder:"Optional…"}),f.sel("visibility","Mặc định ai thấy nhóm",[{value:"public",label:"Công khai"},{value:"authenticated",label:"Người đã đăng nhập"},{value:"private",label:"Riêng tư / được cấp quyền"}],{required:true,help:"Đây là mức hiển thị nhóm; quyền từng tài liệu vẫn được kiểm soát riêng."}),f.sort("sort_order","Thứ tự",{required:true}),f.bool("visible","Hiển thị",{trueLabel:"Hiển thị nhóm"})
]}/>
<TableManager title="Tài liệu / dữ liệu" description="Giao diện đã rút về 2 loại thực tế: Link hoặc tệp R2. Object key R2 được hệ thống quản lý tự động và không cần nhập." table="data_items" orderBy="sort_order" ascending defaults={{storage_mode:"link",visibility:"private",visible:true,metadata:{},item_type:"link"}} fields={[
 f.relation("collection_id","Nhóm",groupRel,{nullable:true,placeholder:"— Không phân nhóm —",help:"Không bắt buộc."}),f.text("title_vi","Tên tài liệu",{required:true,placeholder:"Tài liệu bảo vệ rơ-le"}),f.text("title_en","Tên EN",{placeholder:"Optional…"}),f.area("description_vi","Mô tả",{placeholder:"Tài liệu này dùng để làm gì…"}),f.area("description_en","Mô tả EN",{placeholder:"Optional…"}),
 f.sel("storage_mode","Nguồn tài liệu",[{value:"link",label:"Liên kết — Drive/OneDrive/website khác"},{value:"r2",label:"Tệp R2 — tải file lên hệ thống"}],{required:true,help:"Chỉ có 2 kiểu: link bên ngoài hoặc file được quản lý trong R2."}),
 f.url("external_url","Liên kết",{nullable:true,showWhen:form=>form.storage_mode==="link",requiredWhen:form=>form.storage_mode==="link",derive:form=>form.storage_mode==="link"?form.external_url:null,placeholder:"https://...",help:"Bắt buộc khi Nguồn tài liệu = Liên kết. Nếu chọn Tệp R2 thì ô này có thể để trống.",validate:(v,form)=>form.storage_mode==="link"&&!v?"Hãy nhập liên kết vì bạn đã chọn nguồn Liên kết.":null}),
 f.media("media_id","Tệp R2",{kind:"file",showWhen:form=>form.storage_mode==="r2",requiredWhen:form=>form.storage_mode==="r2",derive:form=>form.storage_mode==="r2"?form.media_id:null,help:"Bắt buộc khi chọn Tệp R2. Upload ngay hoặc chọn ID đã có; object key/tên thư mục do hệ thống tự tạo và không cần nhập.",validate:(v,form)=>form.storage_mode==="r2"&&!v?"Hãy tải/chọn một tệp R2 vì bạn đã chọn nguồn Tệp R2.":null}),
 f.sel("visibility","Ai được xem",[{value:"public",label:"Công khai"},{value:"authenticated",label:"Mọi tài khoản đã đăng nhập"},{value:"private",label:"Chỉ tài khoản được cấp quyền"}],{required:true,help:"Private dùng bảng Cấp quyền phía dưới."}),f.sort("sort_order","Thứ tự",{required:true}),f.bool("visible","Hiển thị",{trueLabel:"Cho tài liệu xuất hiện"}),f.hidden("item_type",{skipSave:false,derive:form=>form.storage_mode==="r2"?"r2_file":"link"}),f.hidden("object_key",{nullable:true}),f.json("metadata","Thông tin mở rộng",{help:"Không bắt buộc. Giữ {} nếu chưa dùng metadata riêng."})
]}/>
<DataAccessMatrix/>
</AdminPage>}
