import React,{useEffect,useMemo,useState}from"react";
import{AdminPage}from"./_shared";
import{assetCode,deleteAsset,getAssetPreviewUrl,listAssets,replaceR2Asset,uploadToR2}from"../lib/media";
import{supabase}from"../lib/supabase";
function size(n=0){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
export default function Media({access}){
 const[rows,setRows]=useState([]),[q,setQ]=useState(""),[file,setFile]=useState(null),[visibility,setVisibility]=useState("public"),[folder,setFolder]=useState("library"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[usage,setUsage]=useState({});
 async function load(){try{setRows(await listAssets("any"));const{data}=await supabase.rpc("get_media_usage_summary");const u={};(data||[]).forEach(x=>u[x.media_id]=x);setUsage(u)}catch(e){setMsg(e.message)}}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(x=>`${assetCode(x.asset_no)} ${x.original_name} ${x.folder} ${x.usage_note} ${x.object_key}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function upload(){if(!file){setMsg("Hãy chọn tệp trước.");return}try{setBusy(true);const a=await uploadToR2(file,{visibility,folder,usageNote:"Thêm từ Thư viện R2"});setMsg(a._deduplicated?`File giống hệt đã tồn tại; dùng lại ${assetCode(a.asset_no)} thay vì upload trùng.`:`Đã lưu ${assetCode(a.asset_no)} vào R2.`);setFile(null);load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function openAsset(a){try{const url=await getAssetPreviewUrl(a);if(!url)throw new Error("Không tạo được URL xem trước.");window.open(url,"_blank","noopener,noreferrer")}catch(e){setMsg(e.message)}}
 async function replace(a,newFile){if(!newFile)return;if(!confirm(`Thay nội dung của ${assetCode(a.asset_no)} nhưng GIỮ NGUYÊN ID? Mọi vị trí đang dùng ID này sẽ nhận file mới.`))return;try{setBusy(true);const r=await replaceR2Asset(a.id,newFile);if(r._replacedByExisting)setMsg(`Không tạo bản trùng: nội dung mới đã có ở ${assetCode(r.asset_no)}. ${assetCode(a.asset_no)} chưa bị thay; hãy chọn ID đã có ở form cần dùng.`);else setMsg(`Đã thay file và giữ nguyên ${assetCode(a.asset_no)}.`);load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function del(a){if(!confirm(`Xóa ${assetCode(a.asset_no)} — ${a.original_name}? ID đã xóa sẽ không được dùng lại.`))return;try{await deleteAsset(a.id,false);setMsg(`Đã xóa ${assetCode(a.asset_no)}.`);load()}catch(e){const force=confirm(`${e.message}\n\nNếu muốn xóa bắt buộc và tự gỡ các liên kết đang dùng ID này, bấm OK.`);if(force){try{await deleteAsset(a.id,true);setMsg(`Đã xóa bắt buộc ${assetCode(a.asset_no)} và gỡ liên kết.`);load()}catch(x){setMsg(x.message)}}else setMsg(e.message)}}
 return <AdminPage access={access}><section className="adminSection"><div className="sectionTitle"><div><h1>Thư viện ảnh & tệp R2</h1><p className="sectionDescription">Nơi xem toàn bộ file website đang quản lý. Các form Cấu hình/SEO/Tool/Tin tức/Phần mềm/CV/User đều có nút tải/chọn R2 ngay tại chỗ, nên không cần upload ở đây rồi đi copy link.</p></div></div>
 <div className="notice"><b>ID R2:</b> R2-000001, R2-000002… tăng tự động và lưu trong database nên đăng xuất/đăng nhập vẫn giữ nguyên. ID đã xóa không tái sử dụng. SHA-256 giúp nhận file giống hệt trong cùng mức công khai để dùng lại ID cũ và tránh tốn dung lượng.</div>
 <div className="mediaToolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm ID R2, tên, thư mục hoặc object key…"/><input value={folder} onChange={e=>setFolder(e.target.value)} placeholder="Thư mục logic, ví dụ software"/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">Public — có URL công khai</option><option value="authenticated">Authenticated — cần đăng nhập</option><option value="private">Private — chỉ signed URL/quyền</option></select><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" onClick={upload} disabled={busy}>{busy?"Đang xử lý…":"Thêm file mới"}</button></div>
 {msg&&<div className="notice">{msg}</div>}
 <div className="mediaLibraryGrid">{shown.map(a=><article key={a.id} className="mediaLibraryCard">{(a.mime_type||"").startsWith("image/")&&a.public_url?<img src={a.public_url} alt=""/>:<div className="fileBadge">{(a.mime_type||"FILE").split("/").pop()?.toUpperCase()}</div>}<strong>{assetCode(a.asset_no)}</strong><span>{a.original_name}</span><small>ID database: {a.id}</small><small>Object key R2: {a.object_key}</small><small>Thư mục: {a.folder} · Quyền: {a.visibility} · {size(a.size_bytes)}</small><small>Mục đích: {a.usage_note||"—"}</small><small>Đang dùng: {usage[a.id]?.usage_count||0} · {(usage[a.id]?.usage_labels||[]).join(", ")||"chưa được trỏ"}</small><div className="rowActions"><button onClick={()=>openAsset(a)}>Xem trước</button><label className="miniButton uploadButton">Thay file, giữ ID<input type="file" hidden onChange={e=>{replace(a,e.target.files?.[0]);e.target.value=""}}/></label><button className="dangerText" onClick={()=>del(a)}>Xóa ID</button></div></article>)}{!shown.length&&<p className="emptyState">Chưa có tệp phù hợp.</p>}</div></section></AdminPage>
}
