import React from"react";import TableManager from"../components/TableManager";import{AdminPage}from"./_shared";import{f}from"../schema";
export default function Seo({access}){return <AdminPage access={access}><TableManager title="SEO từng trang" description="Mỗi dòng là cấu hình SEO cho một route. Đưa chuột vào dấu ? để xem ý nghĩa; ảnh chọn trực tiếp từ R2." table="seo_entries" orderBy="route" ascending defaults={{og_type:"website",indexable:true,follow_links:true,schema_type:"WebPage",change_frequency:"weekly",priority:.7}} fields={[
 f.text("route","Đường dẫn trang",{required:true,placeholder:"/cv",help:"Route cần cấu hình SEO, ví dụ /, /cv, /tools/pdf."}),
 f.text("title_vi","SEO title (VI)",{required:true,placeholder:"Hồ sơ | Nguyễn Lê Khánh Hòa",help:"Tiêu đề hiển thị trên Google/tab. Nên ngắn, rõ và đúng nội dung."}),
 f.text("title_en","SEO title (EN)",{placeholder:"Optional English title"}),
 f.area("description_vi","Meta description (VI)",{placeholder:"Khoảng 1–2 câu mô tả nội dung trang…",help:"Đoạn mô tả mà công cụ tìm kiếm có thể dùng trong kết quả."}),f.area("description_en","Meta description (EN)",{placeholder:"Optional…"}),
 f.text("canonical_path","Canonical path",{nullable:true,placeholder:"/cv",help:"URL chuẩn được ưu tiên khi có nhiều URL trỏ tới cùng nội dung. Thường điền đúng route chính; để trống thì hệ thống dùng route hiện tại."}),
 f.media("og_media_id","Ảnh chia sẻ riêng cho trang",{kind:"image",mirrorUrlField:"og_image",help:"Ảnh preview khi chia sẻ URL trang này. Nếu để trống, dùng OG image mặc định trong Cấu hình chung."}),f.hidden("og_image"),
 f.sel("og_type","Loại Open Graph",[{value:"website",label:"website — trang thông thường"},{value:"article",label:"article — bài viết"},{value:"profile",label:"profile — hồ sơ cá nhân"}],{required:true,help:"Cho mạng xã hội biết loại nội dung khi tạo preview."}),
 f.bool("indexable","Cho lập chỉ mục",{trueLabel:"Cho công cụ tìm kiếm index trang",help:"Tắt nếu không muốn trang xuất hiện trên Google/Bing."}),
 f.bool("follow_links","Cho theo liên kết",{trueLabel:"Cho bot đi theo các liên kết trong trang",help:"Follow links nghĩa là bot tìm kiếm được phép theo các link trong trang để khám phá nội dung liên quan. Tắt tương đương nofollow ở cấp trang."}),
 f.sel("schema_type","Schema",[{value:"WebPage",label:"WebPage — trang thường"},{value:"ProfilePage",label:"ProfilePage — CV/hồ sơ"},{value:"Article",label:"Article — bài viết"},{value:"SoftwareApplication",label:"SoftwareApplication — phần mềm/app"}],{required:true,help:"Schema là loại dữ liệu có cấu trúc giúp máy tìm kiếm hiểu trang nói về gì."}),
 f.json("structured_data","JSON-LD / dữ liệu có cấu trúc",{placeholder:'{\n  "@context": "https://schema.org",\n  "@type": "WebPage"\n}',help:"JSON-LD là nội dung Schema dạng JSON. Nếu chưa cần dữ liệu nâng cao, giữ {}. Hệ thống sẽ báo chính xác nếu JSON sai cú pháp."}),
 f.sel("change_frequency","Tần suất nội dung thay đổi",[{value:"always",label:"Always — thay đổi liên tục"},{value:"hourly",label:"Hourly — hàng giờ"},{value:"daily",label:"Daily — hàng ngày"},{value:"weekly",label:"Weekly — hàng tuần"},{value:"monthly",label:"Monthly — hàng tháng"},{value:"yearly",label:"Yearly — hàng năm"},{value:"never",label:"Never — gần như cố định"}],{required:true,help:"Gợi ý cho sitemap về mức độ cập nhật. CV thường monthly; tin tức có thể daily; trang tĩnh yearly."}),
 f.num("priority","Độ ưu tiên sitemap",{required:true,min:0,max:1,step:.1,placeholder:"0.7",help:"Giá trị 0.0–1.0, chỉ dùng như gợi ý trong sitemap. Trang chủ thường 1.0, trang phụ khoảng 0.5–0.8."})
]}/></AdminPage>}
