import React from"react";import TableManager from"../components/TableManager";import{AdminPage}from"./_shared";import{f}from"../schema";
const catRel={table:"software_categories",select:"id,name_vi,slug,sort_order",valueKey:"id",label:o=>`${o.name_vi} (${o.slug})`,orderBy:"sort_order"};
export default function Software({access}){return <AdminPage access={access}>
<TableManager title="Nhóm phần mềm" description="Nhóm chỉ để lọc/sắp xếp kho phần mềm. Thứ tự tự tăng 1, 2, 3…; không cần tự nhập 10, 20, 30." table="software_categories" orderBy="sort_order" ascending defaults={{visible:true}} fields={[
 f.text("slug","Slug nhóm",{required:true,placeholder:"engineering",help:"Mã nhóm dùng trong dữ liệu. Dùng chữ thường, số và dấu gạch ngang.",validate:v=>v&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v)?"Slug nhóm chỉ dùng a-z, 0-9 và dấu gạch ngang.":null}),f.text("name_vi","Tên nhóm (VI)",{required:true,placeholder:"Kỹ thuật"}),f.text("name_en","Tên nhóm (EN)",{placeholder:"Engineering"}),f.sort("sort_order","Thứ tự",{required:true}),f.bool("visible","Hiển thị",{trueLabel:"Hiển thị nhóm"})
]}/>
<TableManager title="Kho phần mềm" description="Source website chỉ chứa giao diện. Metadata nằm trong Supabase; icon/cover nhỏ có thể lưu R2. Riêng file cài đặt được chọn linh hoạt: dùng link ngoài (Google Drive, OneDrive, MediaFire, website hãng…) hoặc Cloudflare R2." table="software_items" orderBy="sort_order" ascending defaults={{visible:true,featured:false,download_access:"public",download_source:"link",price_label_vi:"Miễn phí",price_label_en:"Free"}} fields={[
 f.text("name","Tên phần mềm",{required:true,placeholder:"EPLAN"}),f.text("slug","Slug",{required:true,placeholder:"eplan",help:"Mã duy nhất của phần mềm; chữ thường, số, dấu gạch ngang.",validate:v=>v&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v)?"Slug chỉ dùng a-z, 0-9 và dấu gạch ngang.":null}),f.relation("category_id","Nhóm",catRel,{nullable:true,placeholder:"— Không phân nhóm —",help:"Chọn nhóm có sẵn; không cần nhập ID."}),
 f.area("description_vi","Mô tả (VI)",{required:true,placeholder:"Phiên bản/công dụng/lưu ý…"}),f.area("description_en","Mô tả (EN)",{placeholder:"Optional…"}),
 f.media("icon_media_id","Icon app trên R2",{kind:"image",mirrorUrlField:"icon_url",visibility:"public",required:true,help:"Bắt buộc. Logo nhỏ lưu R2 hoặc chọn ID R2 đã có; không lưu ảnh trong source."}),f.hidden("icon_url"),
 f.media("cover_media_id","Ảnh cover trên R2",{kind:"image",mirrorUrlField:"cover_url",visibility:"public",help:"Không bắt buộc. Ảnh cover nhỏ có thể lưu R2; không lưu trong source."}),f.hidden("cover_url"),
 f.sel("download_source","Nguồn file tải",[{value:"link",label:"Liên kết ngoài — Google Drive / OneDrive / MediaFire / website khác"},{value:"r2",label:"Cloudflare R2 — upload file trực tiếp"}],{required:true,help:"Chọn Link nếu file lớn hoặc đã lưu ở Drive/website khác để không tốn dung lượng R2. Chọn R2 khi muốn hệ thống quản lý file trực tiếp."}),
 f.url("download_url","Link tải ngoài",{showWhen:form=>form.download_source==="link",requiredWhen:form=>form.download_source==="link",placeholder:"https://drive.google.com/...",derive:form=>form.download_source==="link"?form.download_url:null,help:"Dán link tải đầy đủ. Có thể là Google Drive, OneDrive, MediaFire, website hãng hoặc CDN khác. File không được lưu trong source/R2."}),
 f.media("download_media_id","File cài đặt / file tải trên R2",{kind:"file",showWhen:form=>form.download_source==="r2",requiredWhen:form=>form.download_source==="r2",derive:form=>form.download_source==="r2"?form.download_media_id:null,visibility:form=>form.download_access==="authenticated"?"authenticated":"public",help:"Chỉ bắt buộc khi chọn Cloudflare R2. Nếu file lớn, nên đổi Nguồn file tải sang Liên kết ngoài để tiết kiệm dung lượng R2."}),
 f.sel("download_access","Quyền tải",[{value:"public",label:"Công khai — không cần tài khoản"},{value:"authenticated",label:"Cần đăng nhập mới tải"}],{required:true,help:"Với R2: hệ thống cấp signed URL theo quyền. Với Link ngoài: website chỉ chặn nút tải trước đăng nhập; bản thân link ngoài vẫn do dịch vụ lưu trữ đó kiểm soát."}),
 f.text("price_label_vi","Nhãn giá (VI)",{placeholder:"Miễn phí"}),f.text("price_label_en","Nhãn giá (EN)",{placeholder:"Free"}),f.text("version","Phiên bản",{nullable:true,placeholder:"2026 / v3.1"}),f.text("compatibility","Tương thích",{nullable:true,placeholder:"Windows 10/11 x64"}),f.bool("visible","Hiển thị",{trueLabel:"Hiển thị phần mềm ngoài website"}),f.bool("featured","Nổi bật",{trueLabel:"Ưu tiên app này ở khu/danh sách nổi bật",help:"Bật = phần mềm được ưu tiên lên trước trong danh sách. Tắt = vẫn hiển thị bình thường theo thứ tự."}),f.sort("sort_order","Thứ tự",{required:true})
]}/></AdminPage>}
