import React from"react";import TableManager from"../components/TableManager";import{AdminPage}from"./_shared";import{f}from"../schema";
const roleRel={table:"roles",select:"id,name",valueKey:"id",label:o=>`${o.name} (${o.id})`,orderBy:"id"};
const permissions=[
 {value:"site.manage",label:"Cấu hình website",note:"Site settings, menu, footer."},{value:"content.manage",label:"Nội dung & CV",note:"Trang CMS, CV."},{value:"seo.manage",label:"SEO & Redirect",note:"Metadata, sitemap, redirect."},{value:"tools.manage",label:"Tool",note:"Thêm/sửa/ẩn tool và code HTML."},{value:"news.manage",label:"Tin tức",note:"Bài viết và duyệt bình luận."},{value:"software.manage",label:"Phần mềm",note:"Kho app/phần mềm."},{value:"data.manage",label:"Dữ liệu",note:"Tài liệu và cấp quyền."},{value:"media.manage",label:"Thư viện R2",note:"Upload/xóa/chọn file R2."},{value:"users.manage",label:"Người dùng",note:"Duyệt tài khoản, role, avatar."},{value:"api.manage",label:"API & lịch chạy",note:"Integration, secret, scheduler."},{value:"*",label:"Toàn quyền",note:"Owner: tất cả chức năng."}
];
export default function Users({access}){return <AdminPage access={access}>
<TableManager title="Người dùng" description="Email do Supabase Auth quản lý nên chỉ đọc. Avatar có thể tải trực tiếp lên R2; nếu chưa có avatar, website hiển thị chữ cái viết tắt từ tên người dùng." table="profiles" allowAdd={false} allowDelete={false} orderBy="created_at" fields={[
 f.text("email","Email",{readonly:true}),f.text("display_name","Tên hiển thị",{required:true,placeholder:"Nguyễn Văn A",help:"Nếu chưa có avatar, frontend dùng chữ cái đầu từ tên này làm avatar."}),f.media("avatar_media_id","Avatar",{kind:"image",mirrorUrlField:"avatar_url",help:"Admin có thể tải ảnh người dùng gửi lên R2 hoặc chọn lại ID đã có."}),f.hidden("avatar_url"),f.relation("role_id","Vai trò",roleRel,{required:true,help:"Chọn role bằng tên, không cần nhớ mã quyền."}),f.sel("status","Trạng thái",[{value:"pending",label:"Chờ duyệt"},{value:"active",label:"Đang hoạt động"},{value:"suspended",label:"Tạm khóa"}],{required:true,help:"Pending chưa được dùng các vùng cần tài khoản; Active hoạt động; Suspended bị khóa quyền."})
]}/>
<TableManager title="Vai trò & quyền" description="Không cần gõ code quyền. Tích trực tiếp các chức năng mà vai trò được phép quản lý." table="roles" idField="id" orderBy="id" ascending fields={[
 f.text("id","Mã vai trò",{required:true,placeholder:"editor",help:"Mã kỹ thuật duy nhất; nên tạo một lần rồi giữ ổn định."}),f.text("name","Tên vai trò",{required:true,placeholder:"Biên tập viên"}),f.checkOptions("permissions","Chức năng được phép",permissions,{help:"Tích từng quyền. Nếu tích Toàn quyền (*) thì role có quyền ở mọi Admin module."}),f.area("description","Mô tả vai trò",{placeholder:"Vai trò này dùng cho ai…"})
]}/></AdminPage>}
