import React,{useEffect,useState}from"react";
import{NavLink,useNavigate}from"react-router-dom";
import{supabase,invoke}from"../lib/supabase";
import{notify}from"../lib/notify";
const baseNav=[["/site","Cấu hình chung"],["/navigation","Menu & Footer"],["/content","Trang nội dung"],["/seo","SEO"],["/redirects","Redirect"],["/tools","Danh sách Tool"],["/news","Tin tức"],["/software","Phần mềm"],["/data","Dữ liệu & quyền"],["/cv","CV"],["/users","Người dùng & quyền"],["/media","Thư viện R2"],["/api","API & lịch chạy"]];
function initials(name=""){const p=name.trim().split(/\s+/).filter(Boolean);return(p.slice(-2).map(x=>x[0]?.toUpperCase()).join("")||"U")}
function initialTheme(){try{return localStorage.getItem("nlkh-admin-theme")||"dark"}catch{return"dark"}}
export default function AdminShell({children,access}){const go=useNavigate(),[tools,setTools]=useState([]),[publishing,setPublishing]=useState(false),[toast,setToast]=useState(null),[theme,setTheme]=useState(initialTheme);
 async function loadTools(){const{data}=await supabase.from("tools").select("id,slug,code,title_vi,visible,sort_order").order("sort_order");setTools(data||[])}
 useEffect(()=>{loadTools();const fn=()=>loadTools();window.addEventListener("nlkh:tools-changed",fn);return()=>window.removeEventListener("nlkh:tools-changed",fn)},[]);
 useEffect(()=>{document.documentElement.dataset.adminTheme=theme;try{localStorage.setItem("nlkh-admin-theme",theme)}catch{}},[theme]);
 useEffect(()=>{let timer;const fn=e=>{const d=e.detail||{};setToast({message:d.message||"Đã hoàn tất.",type:d.type||"success"});clearTimeout(timer);timer=setTimeout(()=>setToast(null),Number(d.duration||3200))};window.addEventListener("nlkh:admin-toast",fn);return()=>{clearTimeout(timer);window.removeEventListener("nlkh:admin-toast",fn)}},[]);
 async function logout(){await supabase.auth.signOut();go("/login")}
 async function publish(){if(publishing)return;const ok=confirm("Xuất bản frontend sẽ yêu cầu Render build lại dữ liệu build-time như Menu, Tool, CV, Tin tức, SEO và cấu hình website. Tiếp tục?");if(!ok)return;setPublishing(true);notify("Đang gửi yêu cầu build frontend…","info",5000);try{const r=await invoke("render-deploy",{target:"frontend"});notify(r.message||"Đã yêu cầu Render build lại frontend.","success",5200)}catch(e){notify(e?.message||String(e),"error",9000)}finally{setPublishing(false)}}
 const avatar=access?.avatar_url;return <div className="adminLayout"><aside className="sidebar"><div className="logo">NLKH<br/><span>ADMIN</span></div><nav>{baseNav.map(([to,l])=><React.Fragment key={to}><NavLink to={to}>{l}</NavLink>{to==="/tools"&&tools.length>0&&<div className="toolSubNav">{tools.map(t=><NavLink key={t.id} to={`/tools/${t.id}`} className={({isActive})=>`toolSubItem ${isActive?"active":""}`}>{t.code||"TOOL"} · {t.title_vi}{!t.visible&&" (ẩn)"}</NavLink>)}</div>}</React.Fragment>)}</nav><div className="sidebarFoot"><button onClick={publish} disabled={publishing}>{publishing?"Đang xuất bản…":"Xuất bản frontend"}</button><small className="publishHint">Tool/Menu/CV/News/SEO cần build lại. Data/Software/R2 đọc runtime.</small><button onClick={logout}>Đăng xuất</button></div></aside><main className="adminMain"><header className="adminTop"><div className="adminIdentity"><div className="adminAvatar">{avatar?<img src={avatar} alt=""/>:<span>{initials(access?.display_name||access?.email)}</span>}</div><div><strong>{access?.display_name||access?.email}</strong><small>{access?.role_id}</small></div></div><div className="adminTopActions"><button className="themeToggle" type="button" onClick={()=>setTheme(x=>x==="dark"?"light":"dark")} title="Đổi giao diện sáng/tối">{theme==="dark"?"☀ Sáng":"☾ Tối"}</button><a href={import.meta.env.VITE_SITE_URL||"/"} target="_blank" rel="noreferrer">Mở website ↗</a></div></header>{children}</main>{toast&&<div className={`adminToast ${toast.type||"success"}`}><span>{toast.type==="error"?"!":"✓"}</span><p>{toast.message}</p><button onClick={()=>setToast(null)}>×</button></div>}</div>}
