"use client";
import { useState } from "react";
import styles from "./admin.module.css";

export function MediaUploader() {
  const [file,setFile]=useState<File|null>(null);const [folder,setFolder]=useState("uploads");const [visibility,setVisibility]=useState("public");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function upload(){if(!file)return;setBusy(true);setMessage("Đang chuẩn bị…");try{const signed=await fetch("/api/admin/media/upload-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:file.name,type:file.type||"application/octet-stream",folder})});const signedBody=await signed.json() as { error?: string; uploadUrl: string; key: string; publicUrl?: string };if(!signed.ok)throw new Error(signedBody.error);setMessage("Đang tải trực tiếp lên R2…");const put=await fetch(signedBody.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type||"application/octet-stream"},body:file});if(!put.ok)throw new Error("R2 từ chối tệp. Kiểm tra CORS bucket.");const saved=await fetch("/api/admin/media",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({object_key:signedBody.key,public_url:visibility==="public"?signedBody.publicUrl:null,original_name:file.name,mime_type:file.type||"application/octet-stream",size_bytes:file.size,title:file.name,alt_vi:"",alt_en:"",folder,visibility})});const savedBody=await saved.json() as { error?: string };if(!saved.ok)throw new Error(savedBody.error);setMessage("Đã tải lên và ghi vào thư viện.");setFile(null);}catch(error){setMessage(error instanceof Error?error.message:"Không thể tải tệp.");}setBusy(false)}
  return <section className={styles.resourcePage}><header className={styles.pageHeader}><div><p>R2 / DIRECT UPLOAD</p><h1>Tải ảnh & tệp.</h1><span>Browser tải trực tiếp lên R2 bằng URL ký tạm thời; khóa R2 không xuất hiện ở frontend.</span></div></header><div className={styles.editor}><div className={styles.fields}><label><span>Chọn tệp</span><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label><span>Thư mục</span><input value={folder} onChange={e=>setFolder(e.target.value)}/></label><label><span>Quyền xem</span><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">public</option><option value="authenticated">authenticated</option><option value="private">private</option></select></label></div>{message?<p className={styles.notice}>{message}</p>:null}<button className={styles.save} onClick={upload} disabled={!file||busy}>{busy?"Đang tải…":"Tải lên R2"}<span>↑</span></button></div></section>;
}
