import type { AdminField, ResourcePageConfig } from "./admin-types";

const text = (key: string, label: string, help?: string): AdminField => ({ key, label, help });
const area = (key: string, label: string, help?: string): AdminField => ({ key, label, help, kind: "textarea" });
const bool = (key: string, label: string, help?: string): AdminField => ({ key, label, help, kind: "boolean" });
const num = (key: string, label: string): AdminField => ({ key, label, kind: "number" });
const json = (key: string, label: string, help?: string): AdminField => ({ key, label, help, kind: "json" });
const date = (key: string, label: string): AdminField => ({ key, label, kind: "datetime" });
const select = (key: string, label: string, values: string[]): AdminField => ({ key, label, kind: "select", options: values.map((value) => ({ value, label: value })) });
const ref = (key: string, label: string, resource: string, labelKeys: string[], allowEmpty = true): AdminField => ({ key, label, kind: "reference", reference: { resource, labelKeys, allowEmpty } });

export const configs: Record<string, ResourcePageConfig> = {
  site: { resource:"site-settings", title:"Cấu hình website", description:"Tên miền chỉ nằm trong biến môi trường và bản ghi này; đổi miền không phải sửa mã nguồn.", allowCreate:false, fields:[text("site_name","Tên website"),text("site_url","URL chuẩn"),text("default_title_vi","Tiêu đề mặc định VI"),text("default_title_en","Tiêu đề mặc định EN"),text("title_template","Mẫu title"),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),text("default_og_image","Ảnh OG"),text("contact_email","Email liên hệ"),area("footer_intro_vi","Giới thiệu footer VI"),area("footer_intro_en","Giới thiệu footer EN"),text("copyright_text","Bản quyền"),bool("news_enabled","Bật Tin tức"),bool("registration_enabled","Cho phép đăng ký"),bool("maintenance_mode","Chế độ bảo trì"),json("extra","Cấu hình nội dung mở rộng","Hero, CTA, nhãn và các tùy chọn ít dùng.")] },
  menu: { resource:"menu",title:"Menu động",description:"Thêm, bớt, ẩn và trỏ menu mà không sửa Header. Footer cũng lấy các mục có location footer/both.",itemLabel:"liên kết",fields:[text("label_vi","Nhãn VI"),text("label_en","Nhãn EN"),text("href","Đường dẫn"),select("location","Vị trí",["header","footer","both"]),text("parent_id","ID menu cha"),num("sort_order","Thứ tự"),bool("visible","Hiển thị"),bool("requires_auth","Yêu cầu đăng nhập"),json("allowed_roles","Vai trò được xem","Mảng JSON, ví dụ [\"admin\",\"member\"]"),bool("open_new_tab","Mở tab mới")] },
  socials: { resource:"socials",title:"Liên kết footer",description:"Quản lý mạng xã hội. Có thể xóa GitHub tại đây nếu được thêm lại.",itemLabel:"liên kết",fields:[text("platform","Nền tảng"),text("label","Tên hiển thị"),text("url","URL"),text("icon","Icon"),num("sort_order","Thứ tự"),bool("visible","Hiển thị")] },
  blocks: { resource:"blocks",title:"Nội dung giao diện",description:"Các khối hero, CTA, thống kê và nội dung nhỏ cho từng trang.",itemLabel:"khối",fields:[text("page_key","Mã trang"),text("block_key","Mã khối"),text("label","Tên quản trị"),json("content","Nội dung JSON"),num("sort_order","Thứ tự"),bool("visible","Hiển thị")] },
  pages: { resource:"pages",title:"Trang nội dung",description:"Tạo trang mới không cần sửa frontend. Trang sẽ có địa chỉ /p/slug; sau đó thêm đường dẫn đó vào Menu và SEO.",itemLabel:"trang",fields:[text("slug","Slug (không có dấu /)"),text("title_vi","Tiêu đề VI"),text("title_en","Tiêu đề EN"),area("excerpt_vi","Tóm tắt VI"),area("excerpt_en","Tóm tắt EN"),area("content_vi","Nội dung VI (Markdown)"),area("content_en","Nội dung EN (Markdown)"),select("template","Mẫu giao diện",["standard","wide","article"]),select("status","Trạng thái",["draft","published","archived"]),bool("requires_auth","Yêu cầu đăng nhập"),json("allowed_roles","Vai trò được xem"),date("published_at","Ngày xuất bản")] },
  seo: { resource:"seo",title:"SEO từng trang",description:"Title, mô tả, canonical, Open Graph, robots và schema. Sitemap tự sinh từ các bản ghi được phép lập chỉ mục.",itemLabel:"SEO",fields:[text("route","Đường dẫn"),text("title_vi","Title VI"),text("title_en","Title EN"),area("description_vi","Meta description VI"),area("description_en","Meta description EN"),text("canonical_path","Canonical path"),text("og_image","Ảnh OG"),text("og_type","OG type"),bool("indexable","Cho lập chỉ mục"),bool("follow_links","Cho theo liên kết"),text("schema_type","Schema type"),json("structured_data","Structured data JSON-LD"),select("change_frequency","Tần suất",["always","hourly","daily","weekly","monthly","yearly","never"]),num("priority","Ưu tiên 0–1")] },
  redirects: { resource:"redirects",title:"Chuyển hướng URL",description:"Quản lý redirect trong ứng dụng. Redirect cấp DNS/toàn miền vẫn nên đặt ở Cloudflare.",itemLabel:"redirect",fields:[text("source_path","Đường dẫn nguồn"),text("target_url","URL đích"),select("status_code","Mã",["301","302","307","308"]),bool("active","Hoạt động"),bool("preserve_query","Giữ query string"),area("note","Ghi chú")] },
  tools: { resource:"tools",title:"Danh sách công cụ",description:"Bật/tắt, bảo vệ bằng tài khoản và chọn xuất hiện ở trang chủ/quỹ đạo. Mã chức năng của tool vẫn là module riêng trong source.",itemLabel:"tool",fields:[text("slug","Slug"),text("code","Mã ngắn"),text("route","Đường dẫn"),text("title_vi","Tên VI"),text("title_en","Tên EN"),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),text("icon","Icon hoặc URL ảnh"),text("accent","Màu"),select("status","Trạng thái",["ready","beta","hidden"]),bool("visible","Hiển thị"),bool("show_home","Hiện trang chủ"),bool("show_orbit","Hiện quỹ đạo"),num("orbit_ring","Vòng số"),num("orbit_angle","Góc 0–359"),num("sort_order","Thứ tự"),bool("requires_auth","Yêu cầu tài khoản"),json("allowed_roles","Vai trò được dùng"),json("settings","Cấu hình riêng của tool")] },
  orbit: { resource:"orbit",title:"Các vòng quỹ đạo",description:"Tăng số vòng, tốc độ, chiều quay và điểm sáng. Tool chọn vòng và góc ở trang Cài đặt Tool.",itemLabel:"vòng",fields:[text("id","ID vòng"),num("size","Kích thước %"),num("duration","Số giây/vòng"),bool("reverse","Quay ngược"),bool("dashed","Nét đứt"),num("dot_angle","Góc điểm sáng"),select("dot_tone","Màu điểm",["blue","cyan","orange","violet"]),num("sort_order","Thứ tự"),bool("visible","Hiển thị")] },
  newsCategories: { resource:"news-categories",title:"Chuyên mục tin",description:"Nhóm các bài viết theo chủ đề.",itemLabel:"chuyên mục",fields:[text("slug","Slug"),text("name_vi","Tên VI"),text("name_en","Tên EN"),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),text("color","Màu"),num("sort_order","Thứ tự"),bool("visible","Hiển thị")] },
  news: { resource:"news",title:"Bài viết & tin tức",description:"Quy trình nháp → duyệt → hẹn giờ/xuất bản; có tác giả, người dịch, biên tập, nguồn, tags và ảnh đại diện.",itemLabel:"bài",fields:[text("slug","Slug"),ref("category_id","Chuyên mục","news-categories",["name_vi","slug"]),text("title_vi","Tiêu đề VI"),text("title_en","Tiêu đề EN"),text("subtitle_vi","Phụ đề VI"),text("subtitle_en","Phụ đề EN"),area("excerpt_vi","Tóm tắt VI"),area("excerpt_en","Tóm tắt EN"),area("content_vi","Nội dung VI (Markdown)"),area("content_en","Nội dung EN (Markdown)"),text("cover_image","Ảnh bìa"),text("cover_alt_vi","Alt ảnh VI"),text("cover_alt_en","Alt ảnh EN"),text("author_name","Tác giả"),text("translator_name","Người dịch"),text("editor_name","Biên tập"),text("source_name","Nguồn"),text("source_url","URL nguồn"),json("tags","Tags JSON"),select("status","Trạng thái",["draft","review","scheduled","published","archived"]),bool("featured","Nổi bật"),bool("allow_comments","Cho bình luận"),date("published_at","Ngày xuất bản")] },
  softwareCategories: { resource:"software-categories",title:"Nhóm phần mềm",description:"Nhóm lọc dùng ở kho phần mềm.",itemLabel:"nhóm",fields:[text("slug","Slug"),text("name_vi","Tên VI"),text("name_en","Tên EN"),num("sort_order","Thứ tự"),bool("visible","Hiển thị")] },
  software: { resource:"software",title:"Kho phần mềm",description:"Thêm icon/ảnh, liên kết tải, mô tả và nền tảng. Frontend tự cập nhật từ cơ sở dữ liệu.",itemLabel:"ứng dụng",fields:[text("name","Tên"),text("slug","Slug"),ref("category_id","Nhóm phần mềm","software-categories",["name_vi","slug"]),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),text("icon_url","Icon"),text("cover_url","Ảnh bìa"),text("download_url","Liên kết tải"),text("price_label_vi","Nhãn giá VI"),text("price_label_en","Nhãn giá EN"),text("version","Phiên bản"),text("compatibility","Hệ điều hành"),bool("visible","Hiển thị"),bool("featured","Nổi bật"),num("sort_order","Thứ tự")] },
  dataCollections: { resource:"data-collections",title:"Nhóm dữ liệu",description:"Tạo nhóm công khai, dành cho người đã đăng nhập hoặc cấp riêng.",itemLabel:"nhóm",fields:[text("slug","Slug"),text("name_vi","Tên VI"),text("name_en","Tên EN"),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),text("icon","Icon"),select("visibility","Quyền xem",["public","authenticated","private"]),num("sort_order","Thứ tự"),bool("visible","Hiển thị")] },
  dataItems: { resource:"data-items",title:"Tài liệu & liên kết",description:"Dùng link ngoài hoặc tệp đã tải vào R2. Chọn loại quiz_json để tài khoản được cấp có thể nhập thẳng vào Quiz và chạy local.",itemLabel:"tài liệu",fields:[ref("collection_id","Nhóm dữ liệu","data-collections",["name_vi","slug"]),text("title_vi","Tên VI"),text("title_en","Tên EN"),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),select("item_type","Loại",["link","r2_file","quiz_json","document","video"]),text("external_url","Link ngoài"),text("object_key","R2 object key"),ref("media_id","Tệp trong R2","media",["title","original_name","object_key"]),select("visibility","Quyền xem",["public","authenticated","private"]),num("sort_order","Thứ tự"),bool("visible","Hiển thị"),json("metadata","Metadata JSON")] },
  dataAccess: { resource:"data-access",title:"Cấp quyền dữ liệu",description:"Chọn tài khoản và tài liệu; không cần sao chép UUID. Có thể đặt ngày hết hạn.",itemLabel:"quyền",fields:[ref("user_id","Tài khoản","profiles",["display_name","id"],false),ref("item_id","Tài liệu được cấp","data-items",["title_vi","title_en"],false),date("expires_at","Hết hạn")] },
  cvProfiles: { resource:"cv-profiles",title:"Thông tin CV",description:"Thông tin chính, ảnh, PDF và chủ đề giao diện đều cập nhật từ Admin.",itemLabel:"hồ sơ",fields:[text("name","Họ tên"),text("role_vi","Vai trò VI"),text("role_en","Vai trò EN"),text("headline_vi","Tiêu đề VI"),text("headline_en","Tiêu đề EN"),area("summary_vi","Tóm tắt VI"),area("summary_en","Tóm tắt EN"),text("birth_date","Ngày sinh"),text("address_vi","Địa chỉ VI"),text("address_en","Địa chỉ EN"),text("phone","Điện thoại"),text("email","Email"),text("photo_url","Ảnh"),text("pdf_url","CV PDF"),json("theme","Giao diện JSON"),bool("published","Công khai")] },
  cvSections: { resource:"cv-sections",title:"Các mục CV",description:"Học vấn, kinh nghiệm, chứng chỉ, kỹ năng, dự án và mục tự do.",itemLabel:"mục CV",fields:[ref("profile_id","Hồ sơ CV","cv-profiles",["name"],false),select("section_type","Loại",["experience","education","certificate","skill","project","language","custom"]),text("title_vi","Tiêu đề VI"),text("title_en","Tiêu đề EN"),text("subtitle_vi","Phụ đề VI"),text("subtitle_en","Phụ đề EN"),text("period","Thời gian"),area("description_vi","Mô tả VI"),area("description_en","Mô tả EN"),text("organization","Tổ chức"),text("url","Liên kết"),num("sort_order","Thứ tự"),bool("visible","Hiển thị"),json("data","Dữ liệu bổ sung") ] },
  profiles: { resource:"profiles",title:"Tài khoản",description:"Duyệt, khóa và gán vai trò. Email hiển thị trong danh sách; người mới xác thực email ở trạng thái pending.",itemLabel:"tài khoản",allowCreate:false,fields:[text("display_name","Tên hiển thị"),text("avatar_url","Avatar"),select("role_id","Vai trò",["owner","admin","editor","news_editor","software_manager","data_manager","member"]),select("status","Trạng thái",["pending","active","suspended"])] },
  roles: { resource:"roles",title:"Vai trò & quyền",description:"Quyền dạng JSON array. Owner có [\"*\"].",itemLabel:"vai trò",fields:[text("id","Mã vai trò"),text("name","Tên"),json("permissions","Danh sách quyền"),area("description","Mô tả")] },
  integrations: { resource:"integrations",title:"Kết nối API",description:"Khóa bí mật lưu trong Supabase Vault; browser không nhận được khóa. Chỉ định host cố định để chống gọi nhầm URL.",itemLabel:"API",fields:[text("slug","Mã gọi trong code"),text("name","Tên"),area("description","Mô tả"),text("base_url","Base URL"),text("allowed_host","Host cho phép"),text("endpoint_template","Endpoint template"),select("method","HTTP method",["GET","POST","PUT","PATCH","DELETE"]),json("headers_template","Headers template"),json("query_template","Query template"),json("body_template","Body template"),text("key_placeholder","Ký hiệu khóa"),select("scope","Phạm vi",["public","authenticated","admin"]),num("timeout_ms","Timeout ms"),bool("active","Hoạt động")] },
  jobs: { resource:"jobs",title:"Lịch gọi API",description:"Runner bảo mật được GitHub Actions gọi định kỳ; mỗi job có chu kỳ riêng từ 15 phút.",itemLabel:"lịch",fields:[ref("integration_id","API cần gọi","integrations",["name","slug"]),text("name","Tên lịch"),select("handler","Loại",["integration","supabase_keepalive"]),text("endpoint_path","Endpoint bổ sung"),json("request_payload","Payload JSON"),num("interval_minutes","Chu kỳ phút"),bool("enabled","Bật"),date("next_run_at","Lần chạy kế")] },
  media: { resource:"media",title:"Thư viện R2",description:"Metadata của tệp đã tải lên R2. Trình tải trực tiếp nằm phía trên danh sách.",itemLabel:"tệp",fields:[text("object_key","Object key"),text("public_url","URL công khai"),text("original_name","Tên gốc"),text("mime_type","MIME"),num("size_bytes","Dung lượng byte"),text("title","Tên hiển thị"),text("alt_vi","Alt VI"),text("alt_en","Alt EN"),text("folder","Thư mục"),select("visibility","Quyền xem",["public","authenticated","private"]),text("owner_id","Owner ID")] },
};
