import fs from "node:fs";
const idx=fs.readFileSync("public/tool-modules/pdf/index.html","utf8");
const ui=fs.readFileSync("public/tool-modules/pdf/pdf-ui-v50.js","utf8");
const pv=fs.readFileSync("public/tool-modules/pdf/pdf-preview-v52.mjs","utf8");
const ok=(v,m)=>{if(!v){console.error("FAIL:",m);process.exitCode=1}else console.log("PASS:",m)};
ok(idx.includes('value="splitsmart"')&&idx.includes('value="pdfocr"'),"27-tool additions remain registered");
ok(idx.includes("pdf-ui-v50.js?v=52"),"task UI cache bumped to V52");
ok(idx.includes("pdf-preview-v52.mjs?v=52"),"PDF preview module loaded");
ok(idx.includes("pdf-preview-v52.css?v=52"),"PDF preview CSS loaded");
ok(!idx.includes("pdf-mode-filter-v2.js"),"old global mode filter absent");
ok(ui.includes("NLKH_PDF_CAPABILITIES_V51"),"task-specific capability runtime present");
ok(/split:\{offline:false,online:true\}/.test(ui),"Split does not falsely claim Offline");
ok(ui.includes("split_mode"),"Split API contract fixed");
ok(ui.includes("item.password"),"Unlock password is per-file");
ok(ui.includes("item.rotate"),"Rotate is per-file");
ok(ui.includes("maintain_ratio"),"Resize uses maintain_ratio");
ok(ui.includes("body.x=")&&ui.includes("body.width="),"Crop uses x/y/width/height");
ok(ui.includes("body.to="),"Convert image uses to");
ok(ui.includes("body.elements=[e]"),"Watermark image uses elements[]");
ok(pv.includes("pdfjsLib.getDocument"),"PDF.js rendering used");
ok(pv.includes("IntersectionObserver"),"Thumbnails are lazy-rendered");
ok(pv.includes("deletePageRange"),"Delete thumbnails sync hidden range");
ok(pv.includes("reorderPageOrder"),"Reorder drag syncs page order");
ok(pv.includes("splitRange"),"Split thumbnail selection syncs ranges");
ok(pv.includes("NLKH_PDFJS_VERSION='6.3.289'"),"PDF.js version pinned");
for(const f of ["vendor/pdf.mjs","vendor/pdf.worker.mjs","vendor/PDFJS-LICENSE.txt"]){
  ok(fs.existsSync("public/tool-modules/pdf/"+f),"vendored "+f);
}
if(process.exitCode)process.exit(process.exitCode);
console.log("PDF V52 scoped source checks passed.");
