import fs from "node:fs";
const idx=fs.readFileSync("public/tool-modules/pdf/index.html","utf8");
const u=fs.readFileSync("public/tool-modules/pdf/pdf-ui-v50.js","utf8");
const ok=(v,m)=>{if(!v){console.error("FAIL:",m);process.exitCode=1}else console.log("PASS:",m)};
ok(idx.includes('value="splitsmart"'),"Smart Split registered");
ok(idx.includes('value="pdfocr"'),"OCR registered");
ok(idx.includes("pdf-ui-v50.js?v=51"),"V51 runtime cache version");
ok(idx.includes("pdf-ui-v50.css?v=51"),"V51 CSS cache version");
ok(!idx.includes("pdf-mode-filter-v2.js"),"old global mode filter removed");
ok(u.includes("NLKH_PDF_CAPABILITIES_V51"),"V51 capability registry");
ok(/split:\{offline:false,online:true\}/.test(u),"Split no longer claims incorrect Offline semantics");
ok(/wordpdf:\{offline:false,online:true\}/.test(u),"Word Online-only");
ok(/excelpdf:\{offline:false,online:true\}/.test(u),"Excel Online-only");
ok(/powerpointpdf:\{offline:false,online:true\}/.test(u),"PowerPoint Online-only");
ok(u.includes("split_mode"),"Split sends split_mode");
ok(u.includes("ocr_languages"),"OCR sends ocr_languages");
ok(u.includes("body.prompt"),"Smart Split sends prompt");
ok(u.includes("item.password"),"Unlock password is per-file");
ok(u.includes("item.rotate"),"Rotate is per-file");
ok(u.includes("maintain_ratio"),"Resize uses maintain_ratio");
ok(u.includes("body.x=")&&u.includes("body.width="),"Crop sends x/y/width/height");
ok(u.includes("body.to="),"Convert image uses to");
ok(u.includes("body.elements=[e]"),"Watermark image uses elements[]");
ok(u.includes("pdfjpg_mode"),"PDF to JPG has pages/extract mode");
ok(u.includes("conformance")&&u.includes("allow_downgrade"),"PDF/A settings present");
ok(u.includes("imagePdfPageSize")&&u.includes("merge_after"),"Image to PDF settings present");
ok(u.includes("Passwords do not match"),"Protect validates confirmation");
ok(u.includes("Smart Split PDF with AI"),"English Smart Split label");
ok(u.includes("The document stays on this device."),"Bilingual privacy copy");
if(process.exitCode)process.exit(process.exitCode);
console.log("PDF V51 scoped source checks passed.");
